### ISSUE TITLE
Possibility of returning list of folder ids with folder description/title

### ISSUE THREAD

**Issue by jkatton** [ncssar/sartopo_python#4]
In order to check if a folder exists (for example a radio location archive), I have to make a dummy marker in it with a searchable name in order to find it later.  This is a bit of a headache to create it so that it's not way off in the distance and messing up extents-zooming.  I don't know if it would be possible, but a new call to return all the folder-ids with their title would be very helpful, thanks!

**Comment by caver456** [comment]
already working in 1.0.5; return value structure will change to return entire json feature object for 1.0.6
